name: dotnet package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
      - name: Build solution
        run: dotnet build -c Release
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check if API version changed before pushing packages
        run: bash scripts/check-version.sh
        env:
          BRANCH: ${{ github.base_ref }}