name: Nuget Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
      - name: Save current package version
        run: echo "PACKAGE_VER=`cat package.version`" >> $GITHUB_ENV
      - name: Build & pack solution
        run: dotnet pack -c Release -p:Version="$PACKAGE_VER"
      - name: Push Common nuget
        run: dotnet nuget push "bin/Release/*.Common.*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source "https://api.nuget.org/v3/index.json"
        working-directory: ./Common
      - name: Push Overseer nuget
        run: dotnet nuget push "bin/Release/*.Overseer.*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source "https://api.nuget.org/v3/index.json"
        working-directory: ./Overseer
      - name: Push VirtualizationServer nuget
        run: dotnet nuget push "bin/Release/*.VirtualizationServer.*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source "https://api.nuget.org/v3/index.json"
        working-directory: ./VirtualizationServer

  