name: Nuget Publish

on:
  push:
    branches:
      - main

jobs:
  build:
   runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
      - name: Install versionize
        run: dotnet tool install --global Versionize
      - name: Bump version
        run: versionize
      - name: Build solution
        run: dotnet build -c Release

  publish-overseer:
    runs-on: ubuntu-latest
      - name: Pack Overseer project
        run: dotnet pack -c Release
        working-directory: ./Overseer
      - name: Push Overseer nuget
        run: dotnet nuget push "bin/Release/Overseer.*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source "https://api.nuget.org/v3/index.json"
        working-directory: ./Overseer
        
  publish-virtsrv:
    runs-on: ubuntu-latest
      - name: Pack VirtualizationServer project
        run: dotnet pack -c Release
        working-directory: ./VirtualizationServer
      - name: Push VirtualizationServer nuget
        run: dotnet nuget push "bin/Release/VirtualizationServer.*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source "https://api.nuget.org/v3/index.json"
        working-directory: ./VirtualizationServer
